name: Syscollector test on macOS

on:
  pull_request:
    paths:
        - ".github/workflows/macos-syscollector-tests.yml"
        - "src/data_provider/**"
        - "src/shared_modules/**"
        - "src/wazuh_modules/syscollector/**"
        - "src/Makefile"

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64
      # Build wazuh agent for macOS.
      - name: Build wazuh agent for macOS
        run: |
          rm -rf src/VERSION
          make deps -C src TARGET=agent -j2
          make -C src TARGET=agent -j2
      - name: Install dependencies
        run: |
          pip install -r src/data_provider/qa/requirements.txt
      - name: Run tests
        run: |
          cd src/data_provider
          python -m pytest -vv qa/
